### ISSUE TITLE
multiple nodes

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [perfecto25/poni#4]
How to configure the sync with 4 nodes or more in the config file?
thanks

**Comment by perfecto25** [comment]
you can add as many targets as you want, using remote_host


```
sync:
    /opt/dir1:
        remote_host: host1                ## target host
        remote_path: /opt                   ## target path on remote host
        remote_user: jsmith                 ## user which will initiate rsync
        priv_key: /home/jsmith/.ssh/id_rsa  ## path to user's private SSH key
        port: 1122                          ## custom SSH port, default = 22
        rsync_opts: azBP                    ## additional Rsync flags (default: azP)
        interval: 15                        ## sleep time in seconds before rsyncing on a change, default = 3
        recurse: true                       ## watch directories recursively for changes, default = false

    /var/log/syslog:
        remote_host: host2
        remote_path: /mnt/backup/logs/host123
        remote_user: root
        priv_key: /root/.ssh/id_rsa

    /home/user/data:
        remote_host: host3
        remote_path: /mnt/backup/logs/user/data
        remote_user: root
        priv_key: /root/.ssh/id_rsa

    /home/user/data:
        remote_host: host4
        remote_path: /home/user/
        remote_user: user
        priv_key: /home/user/.ssh/id_rsa

```
